/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import algGeom.Practice4.Pr4a;

/**
 *
 * @author Drebin
 */
public class Menu extends javax.swing.JPanel {

    //Referencia a la pr4 para iniciar las funciones
    private final  Pr4a practica4;
    
    
    /**
     * Creates new form Menu
     * @param _practica4
     */
    public Menu(Pr4a _practica4) {
         
        initComponents();
        this.practica4=_practica4;
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargarNubePuntos = new javax.swing.JButton();
        cargarNubePuntosFich = new javax.swing.JButton();
        nombreFicheroTXT = new javax.swing.JTextField();
        nombreFicheroTSIN = new javax.swing.JTextField();
        cargarFichTSIN = new javax.swing.JButton();
        numPuntos = new javax.swing.JTextField();
        clearScreen = new javax.swing.JButton();
        activateTriangulation = new javax.swing.JButton();
        desactivateTriangulation = new javax.swing.JButton();
        activateCircuferences = new javax.swing.JButton();
        desactivateCircuferences = new javax.swing.JButton();
        activateCH = new javax.swing.JButton();
        desactivateCH = new javax.swing.JButton();

        cargarNubePuntos.setText("Nube Puntos Aleatoria");
        cargarNubePuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarNubePuntosActionPerformed(evt);
            }
        });

        cargarNubePuntosFich.setText("Cargar Nube Puntos");
        cargarNubePuntosFich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarNubePuntosFichActionPerformed(evt);
            }
        });

        nombreFicheroTXT.setText("Nombre Fichero");
        nombreFicheroTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFicheroTXTActionPerformed(evt);
            }
        });

        nombreFicheroTSIN.setText("Nombre Fichero");
        nombreFicheroTSIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFicheroTSINActionPerformed(evt);
            }
        });

        cargarFichTSIN.setText("Cargar Fichero tsin");
        cargarFichTSIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFichTSINActionPerformed(evt);
            }
        });

        numPuntos.setText("Numero de puntos");
        numPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPuntosActionPerformed(evt);
            }
        });

        clearScreen.setText("Limpiar Pantalla");
        clearScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearScreenActionPerformed(evt);
            }
        });

        activateTriangulation.setText("Activar Triangulacion");
        activateTriangulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateTriangulationActionPerformed(evt);
            }
        });

        desactivateTriangulation.setText("Desactivar Triangulacion");
        desactivateTriangulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivateTriangulationActionPerformed(evt);
            }
        });

        activateCircuferences.setText("Activar Circuferencias");
        activateCircuferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateCircuferencesActionPerformed(evt);
            }
        });

        desactivateCircuferences.setText("Desactivar Circunferencias");
        desactivateCircuferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivateCircuferencesActionPerformed(evt);
            }
        });

        activateCH.setText("Activar CH");
        activateCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateCHActionPerformed(evt);
            }
        });

        desactivateCH.setText("Desactivar CH");
        desactivateCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivateCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nombreFicheroTSIN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreFicheroTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(numPuntos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargarNubePuntos)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cargarNubePuntosFich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cargarFichTSIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(desactivateTriangulation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activateTriangulation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(clearScreen)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(desactivateCH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activateCH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desactivateCircuferences, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activateCircuferences, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarNubePuntos)
                    .addComponent(numPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarNubePuntosFich)
                    .addComponent(nombreFicheroTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreFicheroTSIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargarFichTSIN))
                .addGap(18, 18, 18)
                .addComponent(activateTriangulation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desactivateTriangulation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activateCircuferences)
                .addGap(18, 18, 18)
                .addComponent(desactivateCircuferences)
                .addGap(18, 18, 18)
                .addComponent(activateCH)
                .addGap(18, 18, 18)
                .addComponent(desactivateCH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(clearScreen)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarNubePuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarNubePuntosActionPerformed
      
        try{
            //Cargo los puntos
            this.practica4.loadRandomPointCloud(Integer.parseInt(numPuntos.getText()));
            
            //Visualizar
            this.practica4.setVerPuntos(true);
          
        
        }catch(NumberFormatException e){
            System.out.println(e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_cargarNubePuntosActionPerformed

    private void cargarNubePuntosFichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarNubePuntosFichActionPerformed
       
        //Cargar desde fichero
        this.practica4.loadPointCloud(nombreFicheroTXT.getText());
        
        //Visualizar
        this.practica4.setVerPuntos(true);
        
    }//GEN-LAST:event_cargarNubePuntosFichActionPerformed

    private void nombreFicheroTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFicheroTXTActionPerformed
       
    }//GEN-LAST:event_nombreFicheroTXTActionPerformed

    private void cargarFichTSINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFichTSINActionPerformed
        
        this.practica4.loadTsinFich(nombreFicheroTSIN.getText());
        
        this.practica4.setVerPuntos(true);
        
        
    }//GEN-LAST:event_cargarFichTSINActionPerformed

    private void nombreFicheroTSINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFicheroTSINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFicheroTSINActionPerformed

    private void numPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPuntosActionPerformed

    private void activateTriangulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateTriangulationActionPerformed
        
        this.practica4.setVerTriangulos(true);
        
    }//GEN-LAST:event_activateTriangulationActionPerformed

    private void desactivateTriangulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivateTriangulationActionPerformed
       
        this.practica4.setVerTriangulos(false);
        
    }//GEN-LAST:event_desactivateTriangulationActionPerformed

    private void clearScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearScreenActionPerformed
       
        this.practica4.clearAll();
        
    }//GEN-LAST:event_clearScreenActionPerformed

    private void activateCircuferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateCircuferencesActionPerformed
       this.practica4.setVerCircunferencias(true);
    }//GEN-LAST:event_activateCircuferencesActionPerformed

    private void desactivateCircuferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivateCircuferencesActionPerformed
       this.practica4.setVerCircunferencias(false);
    }//GEN-LAST:event_desactivateCircuferencesActionPerformed

    private void activateCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateCHActionPerformed
       this.practica4.setVerCH(true);
    }//GEN-LAST:event_activateCHActionPerformed

    private void desactivateCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivateCHActionPerformed
        this.practica4.setVerCH(false);
    }//GEN-LAST:event_desactivateCHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateCH;
    private javax.swing.JButton activateCircuferences;
    private javax.swing.JButton activateTriangulation;
    private javax.swing.JButton cargarFichTSIN;
    private javax.swing.JButton cargarNubePuntos;
    private javax.swing.JButton cargarNubePuntosFich;
    private javax.swing.JButton clearScreen;
    private javax.swing.JButton desactivateCH;
    private javax.swing.JButton desactivateCircuferences;
    private javax.swing.JButton desactivateTriangulation;
    private javax.swing.JTextField nombreFicheroTSIN;
    private javax.swing.JTextField nombreFicheroTXT;
    private javax.swing.JTextField numPuntos;
    // End of variables declaration//GEN-END:variables
}
